services:
  api:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file: ../.env.example
    ports: ["8080:8080"]
    depends_on: [pg, neo4j]
  pg:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: storage
      POSTGRES_PASSWORD: storage
      POSTGRES_DB: storage
    ports: ["5432:5432"]
  neo4j:
    image: neo4j:5
    environment:
      NEO4J_AUTH: neo4j/neo4j_password
    ports: ["7474:7474", "7687:7687"]