class ChatPort:
    async def append(self, thread_id: str, message: dict, *, idempotency_key: str | None = None) -> None: ...
    async def list(self, thread_id: str, limit: int = 50, before: str | None = None) -> dict: ...
    async def truncate(self, thread_id: str, keep_last_n: int = 0) -> int: ...