class GraphPort:
    async def upsert_entity(self, entity: dict) -> None: ...
    async def relate(self, src: str, dst: str, rel_type: str, props: dict | None = None) -> None: ...
    async def neighbors(self, node_id: str, rel_type: str | None = None, depth: int = 1, filter: dict | None = None) -> dict: ...
    async def delete_entity(self, entity_id: str) -> int: ...
    async def delete_relation(self, src: str, dst: str, rel_type: str) -> int: ...