from typing import Any

class VectorPort:
    async def ensure_collection(self, collection: str, schema: dict[str, Any]) -> None: ...
    async def upsert(self, collection: str, items: list[dict[str, Any]], *, idempotency_key: str | None = None) -> None: ...
    async def query(self, collection: str, embedding: list[float], k: int, filters: dict[str, Any] | None = None, cursor: str | None = None) -> dict[str, Any]: ...
    async def delete(self, collection: str, ids: list[str]) -> int: ...