blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/jonathanwilcox/agent-platform-mvp/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/jonathanwilcox/agent-platform-mvp/blob/main/README.md
    about: Read the project documentation and setup guide